### ISSUE TITLE
[Idea] Vintage Filters

### ISSUE THREAD

**Issue by Magniquick** [TrueMyst/BeatPrints#14]
Saw the plan about Vintage Filters in the readme.
 Imho, might make sense to delegate it to [Lutgen](https://github.com/ozwaldorf/lutgen-rs), if not nothing else, simply due to the sheer amount of work put into it.

**Comment by TrueMyst** [comment]
I feel like adjusting the brightness and the contrast will do the trick!

**Comment by TrueMyst** [comment]
Oh I've added this a very long time ago :>:
