### ISSUE TITLE
[Bug] Libraqm

### ISSUE THREAD

**Issue by itsnotrin** [TrueMyst/BeatPrints#15]
Hi,
I've just moved over from my old laptop running Arch Linux to an M2 MacBook Air. BeatPrints worked perfectly on my Arch machine however on the M2 air I'm receiving

`KeyError: 'setting text direction, language or font features is not supported without libraqm'`
<img width="859" alt="image" src="https://github.com/user-attachments/assets/936ce0ca-08b1-4f35-9c50-e8a480cde81d">

I've installed Python 3.12 and installed libraqm through brew but I still get the error.

Any ideas?

**Comment by itsnotrin** [comment]
I managed to resolve this myself.
The steps were:
```
pip3 uninstall Pillow
pip3 install Pillow --global-option="build_ext" --config-settings="-I = /opt/homebrew/Cellar"
```
Note that this only works if you installed libraqm using brew.

**Comment by TrueMyst** [comment]
Hey @itsnotrin, I've noticed this same issue with Windows! I believe it's a problem with the library itself. Thank you so much for notifying me about it. I'll soon update it in the README.md

**Comment by itsnotrin** [comment]
Of course! I've got a Windows Machine as well so I'll play around with it during some free time today and see if I can find a fix for that

**Comment by TrueMyst** [comment]
Haha, thanks, @itsnotrin! I really appreciate it! I'll be pushing some new updates to this project and making the prompt a lot simpler; do keep an eye on it! Oh, by the way, if you need help with Windows, do let me know. I can assist you with this.
