### ISSUE TITLE
Album Posters

### ISSUE THREAD

**Issue by RUGMJ** [TrueMyst/BeatPrints#16]
I love the look of these posters, do you think it'd be possible to add support for album posters too? Album art, colour bar, track list etc?

If no one wants to implement this i'd be happy to learn the codebase and make a pr myself when I get time

**Comment by TrueMyst** [comment]
Sure! Looks like @itsnotrin did some job for us already :>

**Comment by RUGMJ** [comment]
> Sure! Looks like @itsnotrin did some job for us already :>

We were talking about it elsewhere at the same time as I made this issue lol

**Comment by itsnotrin** [comment]
This can be closed now @TrueMyst

**Comment by RUGMJ** [comment]
weird how gh didn't auto close it, it referenced the issue in the pr 🤔
