### ISSUE TITLE
cannot understand env file

### ISSUE THREAD

**Issue by greyXytOP** [TrueMyst/BeatPrints#3]
i have no idea about what an env file is please help me and tell me how to get tthru the 2nd step in readme.md

**Comment by TrueMyst** [comment]
A .env file is a simple text file that contains a list of environment-specific variables in the form of KEY=VALUE pairs.

So in the .env file you need to put some information like this.

```bash
MUSIXMATCH_API  = "Your Musixmatch API Key"
SPOTIFY_CLIENT_ID = "Your Spotify Client ID"
SPOTIFY_CLIENT_SECRET = "Your Spotify Client Secret"
```

For Musixmatch API, go to [MusixMatch for Developers](https://developer.musixmatch.com/)
For Spotify API go to [Spotify for Developers](https://developer.spotify.com/dashboard/)

Hope this helps!

**Comment by greyXytOP** [comment]
ok that worked but i am unable to get my musixmatch api as the site is not working properly and i cannot login. please help

**Comment by TrueMyst** [comment]
> so i can name the env file anything?

It's better if you stick with the preferred name.

**Comment by greyXytOP** [comment]
Right now I am using it for fun our of curiosity but I may be trying to make printable posters with your program 
 and this can really help me cut the time

**Comment by greyXytOP** [comment]
I got the musixmatch api but it is the free one so I am unable to fetch the lyrics

**Comment by TrueMyst** [comment]
> I got the musixmatch api but it is the free one so I am unable to fetch the lyrics

You don't need to worry about that, I've worked on that part. If you face any errors, let me know.

**Comment by TrueMyst** [comment]
> Right now I am using it for fun our of curiosity but I may be trying to make printable posters with your program and this can really help me cut the time

Are you planning to use it for commercial use?

**Comment by greyXytOP** [comment]
I am facing error it says lyrics not uploaded for every song without plus membership

**Comment by greyXytOP** [comment]
> > Right now I am using it for fun our of curiosity but I may be trying to make printable posters with your program and this can really help me cut the time
> 
> Are you planning to use it for commercial purposes?

Yes I am planning to use it for commercial purposes

**Comment by TrueMyst** [comment]
> > > Right now I am using it for fun our of curiosity but I may be trying to make printable posters with your program and this can really help me cut the time
> > 
> > 
> > Are you planning to use it for commercial purposes?
> 
> Yes I am planning to use it for commercial purposes

Sorry you can't use it for commercial purposes, please read [this](https://github.com/TrueMyst/BeatPrints?tab=readme-ov-file#-about-license)

**Comment by greyXytOP** [comment]
> > > > Right now I am using it for fun our of curiosity but I may be trying to make printable posters with your program and this can really help me cut the time
> > > 
> > > 
> > > Are you planning to use it for commercial purposes?
> > 
> > 
> > Yes I am planning to use it for commercial purposes
> 
> Sorry you can't use it for commercial purposes, please read [this](https://github.com/TrueMyst/BeatPrints?tab=readme-ov-file#-about-license)

i a not using it for commercial purpose anytime soon i was thinking only

**Comment by TrueMyst** [comment]
> > > > > Right now I am using it for fun our of curiosity but I may be trying to make printable posters with your program and this can really help me cut the time
> > > > 
> > > > 
> > > > Are you planning to use it for commercial purposes?
> > > 
> > > 
> > > Yes I am planning to use it for commercial purposes
> > 
> > 
> > Sorry you can't use it for commercial purposes, please read [this](https://github.com/TrueMyst/BeatPrints?tab=readme-ov-file#-about-license)
> 
> i a not using it for commercial purpose anytime soon i was thinking only


Sorry, you cannot use this project for commercial purposes, as this project was made to generate pretty music posters for free. With that being said, I hope you understand the idea of this whole project.

**Comment by TrueMyst** [comment]
> > I am facing error it says lyrics not uploaded for every song without plus membership
> 
> can ya help me with this tho

Can you first show me the .env file in the root directory and also can you show me the error you're facing right at this moment?

**Comment by greyXytOP** [comment]
PS E:\c_prog> & C:/Users/LENOVO/AppData/Local/Programs/Python/Python312/python.exe "e:/download software/BeatPrints-main/BeatPrints-main/src/main.py"
[🌃] Do you want to include a custom image as the cover of the posters? (y/n): n
[🤌] Would you like to add a stylish color accent at the bottom of your poster? (y/n):  n
[🍀] Enter song to search: mera mann bola  
1. Mera Mann Bola by Krishiv Kumar from Mera Mann Bola
2. Behgaye by Karthick from Behgaye
3. 6:30 by MONEY$H from 6:30
4. Mera Mann by Sanjeev Darshan from Mann (Original Motion Picture Soundtrack)       
5. Chalte Reh by AARSH from Chalte Reh
6. Mere Manmohana by Mann Taneja from Mere Manmohana
7. Mera Mann Kehne Laga by Ayushmann Khurrana from Latest Songs Of Ayushmann Khurrana

[✨] Select one of them to show information: 1
Checking lyrics from the database...

1. Mera Mann Bola by Krishiv Kumar

[✨] Just to be sure which lyrics do you want?: 1
 1 Oops, seems like the lyrics aren't posted yet.

[🍀] Select any 4 of favorite lines from here (e.g., 2-5, 7-10):

it shows ' 1 Oops, seems like the lyrics aren't posted yet.' for every song

**Comment by TrueMyst** [comment]
Oh, so basically it checks lyrics on the musixmatch website. If it doesn't exists then there is nothing we can do about it.

**Comment by greyXytOP** [comment]
> Oh, so basically it checks lyrics on the musixmatch website. If it doesn't exists then there is nothing we can do about it. You can see [here](https://www.musixmatch.com/lyrics/Krishiv-Kumar/Mera-Mann-Bola). That's a problem that I'm working on right now!

I tried on many songs and it did not work for any of them. Do let me know if this works out I would be happy to see that

**Comment by TrueMyst** [comment]
> > Oh, so basically it checks lyrics on the musixmatch website. If it doesn't exists then there is nothing we can do about it. You can see [here](https://www.musixmatch.com/lyrics/Krishiv-Kumar/Mera-Mann-Bola). That's a problem that I'm working on right now!
> 
> I tried on many songs and it did not work for any of them. Do let me know if this works out I would be happy to see that

You can try on english songs. They work for sure:)
I'll try to work on this feature as soon as possible.

Thanks anyways! I'll be closing this issue now.

**Comment by greyXytOP** [comment]
> > > Oh, so basically it checks lyrics on the musixmatch website. If it doesn't exists then there is nothing we can do about it. You can see [here](https://www.musixmatch.com/lyrics/Krishiv-Kumar/Mera-Mann-Bola). That's a problem that I'm working on right now!
> > 
> > I tried on many songs and it did not work for any of them. Do let me know if this works out I would be happy to see that
> 
> You can try on english songs. They work for sure:)
> I'll try to work on this feature as soon as possible.
> 
> Thanks anyways! I'll be closing this issue now.

Thanks to you bro I really loved your concept

**Comment by greyXytOP** [comment]
hello i have an idea what if you use genius.com api to fetch lyrics as there are no private lyrics

**Comment by TrueMyst** [comment]
> hello i have an idea what if you use genius.com api to fetch lyrics as there are no private lyrics

I've worked with Genius API before but it's hard to work around with. I'm already working on that feature!

**Comment by greyXytOP** [comment]
> > hello i have an idea what if you use genius.com api to fetch lyrics as there are no private lyrics
> 
> I've worked with Genius API before but it's hard to work around with. I'm already working on that feature!

oh ok thanks ofr the work

**Comment by TrueMyst** [comment]
@greyXytOP I've implemented the feature. I've fixed the lyrics issue, multi-language support and much more! :)

**Comment by greyXytOP** [comment]
> @greyXytOP I've implemented the feature. I've fixed the lyrics issue, multi-language support and much more! :)

oh wow! i would be checking i soon thankyou. love your project
