### ISSUE TITLE
PyPI release?

### ISSUE THREAD

**Issue by aclark4life** [TrueMyst/BeatPrints#8]
This looks cool! Have you considered doing a PyPI release? Need any help with that?

**Comment by TrueMyst** [comment]
Wait, oh my god! I can't believe that it's the founder of Pillow himself. Yes, I do plan to release it in PyPi and put it on a website, maybe! Haha, there is a lot of work to do.

But I'm really glad that you took your time out and checked my project out. This means a lot to me ❤️

**Comment by TrueMyst** [comment]
> This looks cool! Have you considered doing a PyPI release? Need any help with that?

Oh of course yes, if you want to help me out, that'll be awesome!

**Comment by Magniquick** [comment]
Just my two cents, but [pipx](https://pipx.pypa.io/stable/how-pipx-works/#developing-for-pipx) + [github](https://pipx.pypa.io/stable/how-pipx-works/#developing-for-pipx) might be a better choice for this - no need to mess around PyPI stuff, mess with releases (releases don't make much sense for a thing like this imho), and it feels nicer too. 
(Also hola myst ! Nice to see stuff going well here - I'll be free to jump here in two weeks or so.)

**Comment by TrueMyst** [comment]
> Just my two cents, but [pipx](https://pipx.pypa.io/stable/how-pipx-works/#developing-for-pipx) + [github](https://pipx.pypa.io/stable/how-pipx-works/#developing-for-pipx) might be a better choice for this - no need to mess around PyPI stuff, mess with releases (releases don't make much sense for a thing like this imho), and it feels nicer too. (Also hola myst ! Nice to see stuff going well here - I'll be free to jump here in two weeks or so.)

Hmm this makes sense to me, but what about those people who wants to use it as a module?

**Comment by Magniquick** [comment]
who would though ?
It's supposed to be a self contained app right ?
also, pip can do it from git repos too iirc.

**Comment by TrueMyst** [comment]
> who would though ? It's supposed to be a self contained app right ? also, pip can do it from git repos too iirc.

Hmm sounds good to em :)), I'll start working on that

**Comment by aclark4life** [comment]
I would still love a PyPI release! My kingdom for `pip install beatprints` or if I wanted isolation, I'd install it with `pipx install beatprints`.

**Comment by TrueMyst** [comment]
> I would still love a PyPI release! My kingdom for `pip install beatprints` or if I wanted isolation, I'd install it with `pipx install beatprints`.

I would like to release it as `pipx` tool. Though I need some help if you want it as a `pip` package :))

I'll be really glad to see the support for that.

**Comment by qTipTip** [comment]
Hello! 👋 

I like this project too, and would love to see it as a pypi-release!

There is some great documentation on how to do this [here](https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/). 

**But in short:**

- Converting the package to one managed by Poetry might be a good first step: 
https://python-poetry.org/
This will allow you to run `poetry build` to generate distributions (which is what you upload to PyPi). 

- You can then use a GitHub action for instance, I use this one (https://github.com/pypa/gh-action-pypi-publish), to push new versions of your package to PyPi on release. You can see an example [here](https://github.com/qTipTip/Pylette/blob/master/.github/workflows/publish-to-pypi.yaml).

**Comment by TrueMyst** [comment]
@qTipTip Thank you! I’ve been a bit tied up lately, but I’ll publish it as soon as I can.

**Comment by qTipTip** [comment]
Great! 🥳 

You can also define an entrypoint in the `scripts` field in the `pyproject.toml`: https://python-poetry.org/docs/pyproject/#scripts 

So, you can execute the CLI by running: 

```shell
beatprints
```

instead of 

```shell
python3 prompt.py
```

for instance.

**Comment by TrueMyst** [comment]
@aclark4life @qTipTip 

Hey there 👋

I’m excited to share that I’ve finally published BeatPrints to PyPI!

It’s been a busy few days, and I put in my best effort to get it up. While the project currently lacks proper documentation, I’m currently working on it, and any help would be greatly appreciated.

Also, I’m still getting the hang of GitHub Actions. It can be a bit tricky since I’m new to it, but I’m learning as I go.

**Comment by TrueMyst** [comment]
Documentation is finally up!

@aclark4life @qTipTip yaaay!! feel free to check it out now! also fixed the issue with cli! cheers 🍺

**Comment by qTipTip** [comment]
Hey!

Awesome work! I'll have a look when time allows! Merry Christmas! 🎄

**Comment by TrueMyst** [comment]
Hey, great to see you here! Hope you're having an amazing Christmas! Merry Christmas once again! 🎄
