### ISSUE TITLE
Implementation for Apple music or Youtube Music API

### ISSUE THREAD

**Issue by cherriae** [TrueMyst/BeatPrints#9]
> I mean if there is a way to do it.

Some people might not use spotify or have a spotify account or preferably other software.

**Comment by cherriae** [comment]
Also musicxmatch might not have lyrics for every song too

**Comment by TrueMyst** [comment]
> Also musicxmatch might not have lyrics for every song too. Might need pro or smth, I mean Genius has their own [API](https://docs.genius.com/#/getting-started-h1)

I've tried Genius, it turned out to be really slow. Right now I'm working with LyricFind. It's free, and easy to use which can be used as a backup if lyrics are not found. To be frankly honest, it's not possible to get lyrics for each and every song, that's why I've added a feature where it lets you add the lyrics.

**Comment by TrueMyst** [comment]
> I mean if there is a way to do it.
> Some people might not use spotify or have a spotify account or preferably other software.

I believe Spotify is best here in this case because I want to somewhat relate to both of them.

**Comment by cherriae** [comment]
> I believe Spotify is best here in this case because I want to somewhat relate to both of them.

Well this will limit how many people will use your package.

**Comment by TrueMyst** [comment]
> > I believe Spotify is best here in this case because I want to somewhat relate to both of them.
> 
> Well this will limit how many people will use your package.

How?

**Comment by cherriae** [comment]
> > > I believe Spotify is best here in this case because I want to somewhat relate to both of them.
> > 
> > 
> > Well this will limit how many people will use your package.
> 
> How?

Some people use apple music or yt music unless the things use the same api

**Comment by TrueMyst** [comment]
It is possible to implement the same features but time is a factor. It'll take a lot of time to work on that. I'll see what I can do.

**Comment by plyght** [comment]
@TrueMyst Any updates on Apple Music support?
